#Name:Eric Chen
#Email: erchen3pro@gmail.com
#ID:

default:
	gcc -Wall -Wextra -lz -g -o lab1b-client lab1b-client.c
	gcc -Wall -Wextra -lz -g -o lab1b-server lab1b-server.c

clean:
	rm -f *.tar.gz *.txt lab1b-client lab1b-server

dist:
	tar -cvzf lab1b-305099495.tar.gz lab1b-client.c lab1b-server.c README Makefile
