#NAME: Eric Chen
#EMAIL: erchen3pro@gmail.com
#ID: 


default: lab1a.c
	gcc -Wall -Wextra -o lab1a -g lab1a.c
clean:
	rm -f *.txt *.tar.gz lab1a

dist:
	tar -cvzf lab1a-305099495.tar.gz lab1a.c README Makefile 
