#NAME:Julia Wang, Eric Chen 
#EMAIL: julia.wang.ca@gmail.com, erchen3pro@gmail.com	
#UID: 904995934, 305099495

default:
	echo 'python3 lab3b.py $$1' > lab3b
	chmod u+x lab3b
clean:
	rm -f *.tar.gz lab3b
dist:
	tar -czvf lab3b-305099495.tar.gz  lab3b.py Makefile README
